/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A set of keywords that provide a passive effect for a specific upgrade/model.
 */
export interface UpgradeKeywordSet {
  '$May Flip At Start'?: string;
  Cycle?: null;
  Leader?: null;
  Noncombatant?: null;
  Reconfigure?: string;
  Sidearm?: 'Melee' | 'Ranged';
  Small?: null;
  [k: string]: undefined | null | number | string;
}
