/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A set of keywords that provide an action.
 */
export interface ActionKeywordSet {
  Arm?: DefineActionWithExplosive;
  'Calculate Odds'?: DefineAction;
  Distract?: DefineAction;
  Jump?: DefineActionWithAmount;
  Observe?: DefineActionWithAmount;
  'Pulling the Strings'?: DefineAction;
  'Quick Thinking'?: DefineAction;
  Repair?: DefineActionWithCapacity;
  'Secret Mission'?: DefineAction;
  Smoke?: DefineActionWithAmount;
  Spotter?: DefineActionWithAmount;
  Treat?: DefineActionWithCapacity;
  'Take Cover'?: DefineActionWithAmount;
  [k: string]:
    | undefined
    | DefineAction
    | DefineActionWithAmount
    | DefineActionWithCapacity
    | DefineActionWithExplosive;
}
export interface DefineActionWithExplosive {
  actions: number;
  amount: number;
  /**
   * This name must be identical to a weapon on an upgrade or command card.
   */
  explosive: string;
}
export interface DefineAction {
  actions: number;
}
export interface DefineActionWithAmount {
  actions: number;
  amount: number;
}
export interface DefineActionWithCapacity {
  actions: number;
  amount: number;
  capacity: number;
}
