/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Factions that are part of the game.
 */
export type Faction = OfficialFaction | string;
export type OfficialFaction =
  | 'Galactic Empire'
  | 'Galactic Republic'
  | 'Separatist Alliance'
  | 'Rebel Alliance';
