/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DefinePassiveWithActions = [
  'Attack' | 'Dodge' | 'Move',
  ...('Attack' | 'Dodge' | 'Move')[]
];
export type DefinePassiveWithAmount = number;
export type DefinePassive = null;
/**
 * Factions that are part of the game.
 */
export type Faction = ('Galactic Empire' | 'Rebel Alliance') | string;
/**
 * Unit names.
 */
export type UnitName = string;
/**
 * Unit types and sub-types
 */
export type UnitType =
  | 'Trooper'
  | {
      primary: 'Trooper';
      secondary: string;
    }
  | {
      primary: 'Vehicle';
      secondary: string;
    };
/**
 * Upgrade categories in the game.
 */
export type UpgradeType =
  | 'Armament'
  | 'Command'
  | 'Comms'
  | 'Counterpart'
  | 'Crew'
  | 'Force'
  | 'Gear'
  | 'Generator'
  | 'Grenades'
  | 'Hardpoint'
  | 'Heavy Weapon'
  | 'Ordnance'
  | 'Personnel'
  | 'Pilot'
  | 'Training';
export type DefinePassiveWithEffects = [
  (
    | 'Blast'
    | 'Deflect'
    | 'Melee'
    | 'Pierce'
    | 'Pierce (Melee)'
    | 'Range 1 Weapons'
  ),
  ...(
    | 'Blast'
    | 'Deflect'
    | 'Melee'
    | 'Pierce'
    | 'Pierce (Melee)'
    | 'Range 1 Weapons'
  )[]
];
export type DefinePassiveWithSides = [NotchedBaseSide, ...NotchedBaseSide[]];
/**
 * Sides of a notched base.
 */
export type NotchedBaseSide = 'Front' | 'Sides' | 'Rear';

/**
 * A set of keywords that provide a passive effect.
 */
export interface PassiveKeywordSet {
  AI?: DefinePassiveWithActions;
  Agile?: DefinePassiveWithAmount;
  Armor?: DefinePassive | DefinePassiveWithAmount;
  Arsenal?: DefinePassiveWithAmount;
  Authoritative?: DefinePassive;
  Barrage?: DefinePassive;
  Block?: DefinePassive;
  Bounty?: DefinePassive;
  Charge?: DefinePassive;
  'Climbing Vehicle'?: DefinePassive;
  Compel?: DefinePassive;
  Coordinate?: TargetSet;
  Cover?: DefinePassiveWithAmount;
  'Covert Ops'?: DefinePassive;
  Cunning?: DefinePassive;
  'Danger Sense'?: DefinePassiveWithAmount;
  Dauntless?: DefinePassive;
  Defend?: DefinePassiveWithAmount;
  Deflect?: DefinePassive;
  Demoralize?: DefinePassiveWithAmount;
  Detachment?: TargetSet;
  Detonate?: DefinePassiveWithExplosive;
  Disciplined?: DefinePassiveWithAmount;
  Disengage?: DefinePassive;
  'Djem So Mastery'?: DefinePassive;
  Duelist?: DefinePassive;
  Enrage?: DefinePassiveWithAmount;
  Entourage?: TargetSet;
  Equip?: TargetSet;
  Exemplar?: DefinePassive;
  'Expert Climber'?: DefinePassive;
  'Field Commander'?: DefinePassive;
  'Fire Support'?: DefinePassive;
  Flawed?: DefinePassive;
  'Full Pivot'?: DefinePassive;
  Generator?: DefinePassiveWithAmount;
  Grounded?: DefinePassive;
  Guardian?: DefinePassiveWithAmount;
  Gunslinger?: DefinePassive;
  'Heavy Weapon Team'?: DefinePassive;
  Hover?: DefinePassiveWithTerrain;
  Immune?: DefinePassiveWithEffects;
  Impervious?: DefinePassive;
  Incognito?: DefinePassive;
  Inconspicuous?: DefinePassive;
  Indomitable?: DefinePassive;
  Infiltrate?: DefinePassive;
  Inspire?: DefinePassiveWithAmount;
  'Jedi Hunter'?: DefinePassive;
  'Juyo Mastery'?: DefinePassive;
  'Light Transport'?: DefinePassiveWithTransport;
  Loadout?: DefinePassive;
  'Low Profile'?: DefinePassive;
  'Makashi Mastery'?: DefinePassive;
  Marksman?: DefinePassive;
  'Master of the Force'?: DefinePassiveWithAmount;
  Nimble?: DefinePassive;
  Outmaneuver?: DefinePassive;
  Plodding?: DefinePassive;
  Precise?: DefinePassiveWithAmount;
  Ready?: DefinePassiveWithAmount;
  Recharge?: DefinePassiveWithAmount;
  Regenerate?: DefinePassiveWithAmount;
  Relentless?: DefinePassive;
  Reliable?: DefinePassiveWithAmount;
  Reposition?: DefinePassive;
  Retinue?: TargetSet;
  Scale?: DefinePassive;
  Scout?: DefinePassiveWithAmount;
  'Scouting Party'?: DefinePassiveWithAmount;
  Sentinel?: DefinePassive;
  Sharpshooter?: DefinePassiveWithAmount;
  Shielded?: DefinePassiveWithAmount;
  'Soresu Mastery'?: DefinePassive;
  Speeder?: DefinePassiveWithAmount;
  Spur?: DefinePassive;
  Stationary?: DefinePassive;
  Steady?: DefinePassive;
  Tactical?: DefinePassiveWithAmount;
  Target?: DefinePassiveWithAmount;
  Teamwork?: TargetSet;
  Tempted?: DefinePassive;
  Transport?: DefinePassiveWithTransport;
  'Uncanny Luck'?: DefinePassiveWithAmount;
  Unhindered?: DefinePassive;
  Versatile?: DefinePassive;
  'Weak Point'?: DefinePassiveWithSides;
  'Wheel Mode'?: DefinePassive;
  [k: string]:
    | undefined
    | DefinePassive
    | DefinePassiveWithActions
    | DefinePassiveWithAmount
    | DefinePassiveWithEffects
    | DefinePassiveWithExplosive
    | DefinePassiveWithSides
    | TargetSet
    | DefinePassiveWithTransport
    | DefinePassiveWithTerrain;
}
/**
 * A set of units, types, ranks, targeted by an effect.
 */
export interface TargetSet {
  /**
   * Factions. Multiple entries is treated as an OR.
   */
  factions?: Faction[];
  /**
   * Force alignments. Multiple entries is treated as an OR.
   */
  forceAlignment?: ('Light Side' | 'Dark Side')[];
  /**
   * Unit names. Multiple entries is treated as an OR.
   */
  units?: UnitName[];
  /**
   * Unit ranks. Multiple entries is treated as an OR.
   */
  unitRanks?: UnitRank[];
  /**
   * Unit types. Multiple entries is treated as an OR.
   */
  unitTypes?: UnitType[];
  /**
   * This unit or effect is unique (once per list or per game).
   */
  isUnique?: true;
  /**
   * Units that have an upgrade icon. Multiple entries is treated as an OR.
   */
  hasUpgradeSlot?: UpgradeType[];
}
export interface DefinePassiveWithExplosive {
  amount: number;
  /**
   * This name must be identical to a weapon on an upgrade or command card.
   */
  explosive: string;
}
export interface DefinePassiveWithTerrain {
  type: 'Air' | 'Ground';
  height: number;
}
export interface DefinePassiveWithTransport {
  type: 'Open' | 'Closed';
  capacity: number;
}

/**
 * Ranks that are part of the game. These values are not customizable for custom content.
 */
export const enum UnitRank {
  Commander = 'Commander',
  Operative = 'Operative',
  Corps = 'Corps',
  SpecialForces = 'Special Forces',
  Support = 'Support',
  Heavy = 'Heavy',
}
