/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RuleSet =
  | {
      SWL: number;
    }
  | {
      RRG: string | ('Homebrew' | 'Unknown');
    };

export interface PointAdjustments {
  since: RuleSet;
  units: NamedCards;
  upgrades: NamedCards;
}
export interface NamedCards {
  [k: string]: number;
}
