/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Factions that are part of the game.
 */
export type Faction = ("Galactic Empire" | "Rebel Alliance") | string;
/**
 * Unit types and sub-types
 */
export type UnitType =
  | "Trooper"
  | {
      name: "Trooper";
      type: string;
    }
  | {
      name: "Vehicle";
      type: string;
    };
/**
 * Range in the game.
 */
export type Range = ("Melee" | "Infinite" | number)[];

/**
 * Defines a unit card.
 */
export interface UnitCard {
  /**
   * Name of the unit.
   */
  name: string;
  faction: Faction;
  points: number;
  /**
   * Optional sub-title for the unit card.
   */
  title?: string;
  rank: UnitRank;
  /**
   * Number of miniatures in the unit.
   */
  miniatures: number;
  type: UnitType;
  defense: Defense;
  attack?: Offense;
  speed: number;
  upgrades: {
    [k: string]: number;
  };
  weapons: [Weapon] | [Weapon, Weapon] | [Weapon, Weapon, Weapon];
}
export interface Defense {
  color: DefenseDice;
  surges?: true;
  wounds: number;
  courage?: number;
  resilience?: number;
}
export interface Offense {
  surges: "Hit" | "Crit";
}
/**
 * Weapon definition.
 */
export interface Weapon {
  name: string;
  range: Range;
  dice: AttackPool;
}
/**
 * A pool of attack dice.
 */
export interface AttackPool {
  White?: number;
  Black?: number;
  Red?: number;
}

/**
 * Rank of the unit
 */
export const enum UnitRank {
  Commander = "Commander",
  Operative = "Operative",
  Corps = "Corps",
  SpecialForces = "Special Forces",
  Support = "Support",
  Heavy = "Heavy"
}
/**
 * Defense dice in the game.
 */
export const enum DefenseDice {
  White = "White",
  Red = "Red"
}
