/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Defines the sides of a notched unit.
 */
export const enum UnitSide {
  Front = "Front",
  Sides = "Sides",
  Rear = "Rear"
}
