/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Ranks that are part of the game. These values are not customizable for custom content.
 */
export const enum UnitRank {
  Commander = "Commander",
  Operative = "Operative",
  Corps = "Corps",
  SpecialForces = "Special Forces",
  Support = "Support",
  Heavy = "Heavy"
}
