/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Upgrade categories in the game.
 */
export type UpgradeType = OfficialUpgradeType | string;
export type OfficialUpgradeType =
  | "Armament"
  | "Command"
  | "Comms"
  | "Counterpart"
  | "Crew"
  | "Force"
  | "Gear"
  | "Generator"
  | "Grenades"
  | "Hardpoint"
  | "Heavy Weapon"
  | "Ordnance"
  | "Personnel"
  | "Pilot"
  | "Training";
